zg: 256
zd: 3
c_req: [
  'UNetC','DNetC'
]
img_size: 256
generator: [
  [ -1,1,UNetC,[ 512,False,'nn.ReLU(True)' ] ],
  [ -1,1,UNetC,[ 728,False,'nn.ReLU(True)' ] ],
  [ -1,1,UNetC,[ 1024,False,'nn.ReLU(True)' ] ],
#  [ -1,1,UNetC,[ 728,False,'nn.ReLU(True)' ] ],
  [ -1,1,UNetC,[ 512,False,'nn.ReLU(True)' ] ],
  [ -1,3,UNetC,[ 400,False,'nn.ReLU(True)' ] ],
  [ -1,3,UNetC,[ 300,False,'nn.ReLU(True)' ] ],
  [ -1,1,UNetC,[ 200,False,'nn.ReLU(True)' ] ],
  [ -1,1,UNetC,[ 3,False,'nn.Tanh()' ] ],

]

discriminator: [
  [ -1,1,DNetC,[ 64,False,'nn.LeakyReLU(True,inplace=0.2)' ] ],
#  [ -1,1,DNetC,[ 64,False,'nn.LeakyReLU(True,inplace=0.2)' ] ],
  [ -1,3,DNetC,[ 64,False,'nn.LeakyReLU(True,inplace=0.2)' ] ],
  [ -1,1,DNetC,[ 128,False,'nn.LeakyReLU(True,inplace=0.2)' ] ],
  [ -1,3,DNetC,[ 256,False,'nn.LeakyReLU(True,inplace=0.2)' ] ],
  [ -1,1,DNetC,[ 512,False,'nn.LeakyReLU(True,inplace=0.2)' ] ],
  [ -1,1,DNetC,[ 728,False,'nn.LeakyReLU(True,inplace=0.2)' ] ],
  [ -1,1,DNetC,[ 728,False,'nn.LeakyReLU(True,inplace=0.2)' ] ],
  [ -1,1,DNetC,[ 1024,False,'nn.Sigmoid()',False ] ],
]
