z: 90
n_classes: 5
image_channels: 3
image_size: 34

generator: [
  #from, number ,name [arg :  output, kernel, stride ,final layer]
  [ -1,1,GeneratorBlock,[ 512,4,1,0,False,'nn.ReLU(True)' ] ],
  [ -1,1,GeneratorBlock,[ 256,4,2,1,False,'nn.ReLU(True)' ] ],
  [ -1,1,GeneratorBlock,[ 128,4,2,1,False,'nn.ReLU(True)' ] ],
  [ -1,1,GeneratorBlock,[ 64,4,1,1,False,'nn.ReLU(True)' ] ],
  [ -1,1,GeneratorBlock,[ 3,4,2,1,False,'nn.Tanh()' ] ],

]

discriminator: [
  [ -1,1,DiscriminatorBlock,[ 64,3,2,1,False,'nn.LeakyReLU(True,inplace=0.2)' ] ],
  [ -1,1,DiscriminatorBlock,[ 128,4,1,1,False,'nn.LeakyReLU(True,inplace=0.2)' ] ],
  [ -1,1,DiscriminatorBlock,[ 256,4,1,1,False,'nn.LeakyReLU(True,inplace=0.2)' ] ],
  [ -1,1,DiscriminatorBlock,[ 512,4,1,1,False,'nn.LeakyReLU(True,inplace=0.2)' ] ],
  [ -1,1,DiscriminatorBlock,[ 512,4,2,1,False,'nn.LeakyReLU(True,inplace=0.2)' ] ],
  [ -1,1,DiscriminatorBlock,[ 512,4,2,1,False,'nn.LeakyReLU(True,inplace=0.2)' ] ],
  [ -1,1,DiscriminatorBlock,[ 1,3,1,0,True ,'nn.Sigmoid()' ] ],
]
